### ISSUE TITLE
Safe Mode when using tweet song

### ISSUE THREAD

**Issue by leo98gomez** [CPDigitalDarkroom/HideMeX-iOS-10#1]
Whenever I have the tweet song option I go into safe mode after the 10 seconds it supposed to tweet it. It seems it only happens with Deezer, but not with Spotify. 
Crash report sent. I had sent another one about it but this one is from v 1.0.0.1

**Comment by CPDigitalDarkroom** [comment]
Fixed as of v1.0.0.3
