### ISSUE TITLE
HMX now conflicts with Cream 2 when installed but doesn't offer FlipControlCenter support for color toggles

### ISSUE THREAD

**Issue by kgfromthemv** [CPDigitalDarkroom/HideMeX-iOS-10#11]
Pretty much title. Just updated HMX and it forced me to remove Cream 2 but HMX doesn't support FlipControlCenter toggles which was the whole reason I was using Cream 2...

**Comment by leo98gomez** [comment]
Hidemex has cream 2 settings in it under CC

**Comment by kgfromthemv** [comment]
Yes, but it doesn't offer support for FlipControlCenter toggles, only the stock toggles.

**Comment by CPDigitalDarkroom** [comment]
FlipControlCenter support has been added as of v1.0.1.1+
