### ISSUE TITLE
Seconds don't update on custom statusbar string

### ISSUE THREAD

**Issue by moshed** [CPDigitalDarkroom/HideMeX-iOS-10#13]
The seconds just remain at 00 but everything else changes as normal. 
![img_6e7df21811c2-1](https://cloud.githubusercontent.com/assets/8683379/23411885/c52a3b8e-fda1-11e6-9dd0-98e3c4c6529c.jpeg)

**Comment by CPDigitalDarkroom** [comment]
Did you enable the Uses seconds in Formatter option?

**Comment by moshed** [comment]
i put `ss` in the custom time formatter as pictured above. is there a different way to do it?

**Comment by CPDigitalDarkroom** [comment]
s or ss depending on if you want it padding with 0's. s = 1 ss = 01

**Comment by moshed** [comment]
i tried both but its not updating it just stays at whatever second i set it at but then changes to 00 when the minute changes and stays like that

**Comment by CPDigitalDarkroom** [comment]
With the option for seconds enabled above it?

**Comment by moshed** [comment]
i did toggle it and it still wasnt working even after i tapped on the custom string so the save button appeared and pressed save. i had to change the custom string press save then re add the seconds in. now its working! thanks!

out of curiosity why even have that option? if the `s` is included it should follow that the user wants seconds

**Comment by CPDigitalDarkroom** [comment]
Because I was being lazy and didn't want to parse the user string for "s" or "ss". I've changed it with the latest code to do just that and remove that option from existing. 

Issue fixed in v1.0.3+

**Comment by moshed** [comment]
ha i just saw that commit. holy shit that was quick

**Comment by CPDigitalDarkroom** [comment]
I'll closing this issue as the new build essentially fixes this to no longer be an issue which can be produced.
