### ISSUE TITLE
custom opacity requires a respring partially

### ISSUE THREAD

**Issue by moshed** [CPDigitalDarkroom/HideMeX-iOS-10#14]
when originally toggling it it no respring is required but after trying to change the settings around to fine tune it to my taste it doesnt change unless repsrung (resprang?, respringed?)

**Comment by CPDigitalDarkroom** [comment]
Custom opacity for which setting?

**Comment by moshed** [comment]
ooh sorry for control center darkening view

**Comment by CPDigitalDarkroom** [comment]
Fixed as of v1.0.8
