### ISSUE TITLE
Custom Time Format Descriptions

### ISSUE THREAD

**Issue by snowgoer540** [CPDigitalDarkroom/HideMeX-iOS-10#17]
Timezone is missing the z before |

Also, Z shows how many hours are subtracted, idk if it's useful to add that or not but I thought I would throw it out there.

Lowercase AM/PM doesnt seem to apply when the custom formatter is used.  Also, Is there a way to show just A or P (of AM and PM)?

Lastly, what does "Disable Breadcrumbs" do?

**Comment by CPDigitalDarkroom** [comment]
Custom time formatters will adhere to the lowercase AM/PM option as of v1.0.2+

**Comment by snowgoer540** [comment]
Thanks Carlos.  For the record, the "z" is still missing in the descriptions of the modifiers before the | .

**Comment by CPDigitalDarkroom** [comment]
Took me a bit to realize where you meant it. v1.0.3 will fix this.
