### ISSUE TITLE
Request: Hide "x may slow down your iPhone"

### ISSUE THREAD

**Issue by iAdam1n** [CPDigitalDarkroom/HideMeX-iOS-10#19]
I'm requesting an option to disable the popup that says ""APPNAME" May Slow Down Your iPhone".

**Comment by CPDigitalDarkroom** [comment]
I've included this feature in v1.0.2, I tested with one app but future tests from others would be preferable once it's live before I close this issue.

**Comment by iAdam1n** [comment]
Awesome, thanks!
