### ISSUE TITLE
No Sim Alerts not suppressing

### ISSUE THREAD

**Issue by biird** [CPDigitalDarkroom/HideMeX-iOS-10#32]
I have the No Sim Alerts toggle selected to remove the alert on my iPad Mini 2 (iOS 10.2 w/o sim card inserted), but still getting No Sim Installed after every respring. Not sure if the alert supressing is working yet on iOS 10, but just wanted to let you know. Let me know if you need a log/list of installed apps/etc

**Comment by CPDigitalDarkroom** [comment]
Fixed in build 1.0.6.
