### ISSUE TITLE
Passcode string options bugged

### ISSUE THREAD

**Issue by BLINK1337** [CPDigitalDarkroom/HideMeX-iOS-10#34]
When toggling one of the options for Passcode strings to on, it moves the text box down and steals the text from a different string. Keeps moving down with every toggle on and off. Left a video showing what I mean in the HMX slack channel.

**Comment by CPDigitalDarkroom** [comment]
Should be fixed as of v 1.0.5

**Comment by BLINK1337** [comment]
This is fixed now v1.0.5
