### ISSUE TITLE
Lock screen Passcode strings bug

### ISSUE THREAD

**Issue by BLINK1337** [CPDigitalDarkroom/HideMeX-iOS-10#35]
The custom string option for "your passcode is required to enable TouchID" doesn't work.

**Comment by CPDigitalDarkroom** [comment]
Should be fixed as of v.1.0.5. Let me know when you install it if it does .

**Comment by BLINK1337** [comment]
Still broken :(

**Comment by CPDigitalDarkroom** [comment]
Fixed as of 1.0.6
