### ISSUE TITLE
Can't launch apps when 3D Touch menu is active

### ISSUE THREAD

**Issue by pdrsjr** [CPDigitalDarkroom/HideMeX-iOS-10#37]
If I 3D Touch an icon, while the pop up menu is active, tapping the icon to launch the app does nothing. I have to tap outside of the menu or press the home button to launch it normally. 

This isn't really a huge issue but it's a minor detail that's kind of annoying. 

iPhone 6s+ iOS 10.2 on version 1.0.5 of HMX.

**Comment by CPDigitalDarkroom** [comment]
Fixed as of build 1.0.6
