### ISSUE TITLE
Unrounded corners when updating app

### ISSUE THREAD

**Issue by moshed** [CPDigitalDarkroom/HideMeX-iOS-10#39]
when toggling "dont darken with tap" option in "icons" settings updating an icon gives you this unrounded corners overlay 
![img_0226](https://cloud.githubusercontent.com/assets/8683379/23600571/34cbf03c-0215-11e7-96fc-39ad0c5dc66e.JPG)

**Comment by CPDigitalDarkroom** [comment]
Fixed as of v1.0.6
