### ISSUE TITLE
Idea: always display Battery Widget

### ISSUE THREAD

**Issue by matruka** [CPDigitalDarkroom/HideMeX-iOS-10#41]
So i got an Apple Watch recently and noticed the stock apple battery widget only appears if you have a second device connected. 
Is it possible to make the battery widget stay there the whole time showing just the iPhone battery? like connecting a new device will add this device to the widget and disconnecting will just remove it from there leaving the iphone's batterie.

I hope you understood what i was trying to request :D would be a pretty cool feature

**Comment by CPDigitalDarkroom** [comment]
Available option as of the v1.0.7 update
