### ISSUE TITLE
Disabling control center darkening view options does not return to default behavior

### ISSUE THREAD

**Issue by pdrsjr** [CPDigitalDarkroom/HideMeX-iOS-10#45]
I enabled some of these settings but disabled them since they weren't important to me. Now whenever I pull up control center I'm somehow able to interact with the app behind control center and there's no slight darkening of the screen like normal iOS. I assumed disabling modifications would make it return to its normal behavior. Current workaround for this is to enable the custom opacity.

iPhone 6s+. iOS 10.2. HMX 1.0.8

**Comment by CPDigitalDarkroom** [comment]
Fixed in HMX 1.0.9
