### ISSUE TITLE
SpringBoard crashing on activator gesture

### ISSUE THREAD

**Issue by finessarae** [CPDigitalDarkroom/HideMeX-iOS-10#47]
[PACKAGE LIST](http://pastebin.com/FxhNzUSx)
[CRASH LOG](http://pastebin.com/CrYqPHRU)

Specifically during swipe up/down gesture used to adjust screen brightness with Brightness Activator Pro. Initial gesture (swipe onto screen from top right) to enable edit mode works just fine. Disabling HideMeX using iCleaner solved the issue. Is there anyway around the conflict?

**Comment by CPDigitalDarkroom** [comment]
I was not able to replicate the crash with BAP. From your crash log I deduced the most likely cause and have applied a patch to fix it in v 1.0.9. Once the update is available, check if the crash still occurs.

**Comment by finessarae** [comment]
Thank youuu! Really appreciate it.
I'll let you know the verdict post-update 👽

**Comment by finessarae** [comment]
Works like a gem after upgrade! Thanks again :)
