### ISSUE TITLE
Statusbar seconds don't update. 

### ISSUE THREAD

**Issue by BLINK1337** [CPDigitalDarkroom/HideMeX-iOS-10#5]
When using a custom time string and including seconds, they do not update. They seem to load at certain intervals (respring is all I know for certain) and that's all, so they're essentially always wrong.

**Comment by CPDigitalDarkroom** [comment]
Fixed as of v1.0.0.2

**Comment by moshed** [comment]
im still having this issue as reported here #13 on 1.0.2

**Comment by BLINK1337** [comment]
There is a switch just above where you enter the custom time string now that says "uses seconds". Enable that and respring, worked for me at least. 
Give it a shot and see what happens.
