### ISSUE TITLE
Control Center pages when using Horseshoe

### ISSUE THREAD

**Issue by montanio** [CPDigitalDarkroom/HideMeX-iOS-10#55]
Is it possible to remove the left bottom corner page button that appears in Control Center when you have Horseshoe installed? I don't know if this is actually a bug but I don't it should exist because the are no pages in Horseshoe.

**Comment by CPDigitalDarkroom** [comment]
This would be something Horseshoe does.

**Comment by montanio** [comment]
Noted. Thanks for your reply.
