### ISSUE TITLE
Hide Share Option in 3d touch causing blank 3d touch screen

### ISSUE THREAD

**Issue by indianheart4u** [CPDigitalDarkroom/HideMeX-iOS-10#8]
After turning on the option to hide share from 3d touch, the share option gets removed but it shows up a blank blurred screen for apps which do not have any 3d touch options..

**Comment by kgfromthemv** [comment]
Can confirm this is also happening for me as well.

**Comment by kgfromthemv** [comment]
Can confirm this is also happening for me as well.

**Comment by CPDigitalDarkroom** [comment]
Fixed as of v 1.0.0.2
