### ISSUE TITLE
Odd Behavior when disabling Replace with Blur

### ISSUE THREAD

**Issue by leo98gomez** [CPDigitalDarkroom/HideMeX-iOS-10#9]
If you enable Replace with Blur under Control center then turn it off, the blue goes away but you are able to interact with the background of the CC. By interact, I mean that you can Scroll/tap whatever is above the control center(where the blur/shadow usually is) when it's invoked. This behavior or does occur on the home screen but in apps

**Comment by CPDigitalDarkroom** [comment]
The issue has been fixed and will be patched in build v1.0.2+
